name: Create Infra with Terraform

on:
  push:
    branches:
      - main  # Only trigger on push to main

jobs:
  terraform:
    name: Terraform Create Infra
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (only on main)
        if: github.ref == 'refs/heads/main'
        run: terraform plan -out=tfplan

      - name: Terraform Destroy (on destroy branch)
        if: github.ref == 'refs/heads/main'
        run: terraform destroy -auto-approvetfplan
